#lang racket
(define (make-account balance passwd)
  (define (withdraw amount)
    (let ((new-balance (- balance amount)))
      (if (< new-balance 0)
          (display "insufficient funds")
          (begin
            (set! balance new-balance)
            new-balance))))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (show) balance)
  (define (incorrect-passwd x) (display "Incorrect password"))
  (define (dispatch . m)
    (if (eq? (car m) passwd)
         (cond ((eq? (cadr m) 'withdraw) withdraw)
               ((eq? (cadr m) 'deposit) deposit)
               ((eq? (cadr m) 'show-balance) show)
               (else (error "MAKE-ACCT bad op" m)))
        incorrect-passwd))
  dispatch)
(define acc (make-account 100 'asdf))